gg:
  jte:
    development-mode: true
    use-precompiled-templates: false
    template-location: src/main/jte
    content-type: text/html;charset=UTF-8
    compile-args:
      - --jte-runtime-version=V3_1_0
      - --strip-whitespace=true

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: redefinirsenhasystem6@gmail.com
    password: fcvh fwwg bdcd uzms 
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: false  # Desative em produção

  datasource:
    url: jdbc:h2:mem:quiosque
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8083

logging:
  level:
    root: INFO
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR
    org.springframework.orm.jpa: DEBUG
    gg.jte: DEBUG  # Adicionado para logs do JTE